[package]
name = "protoworm"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
cortex-m-semihosting = "0.5.0"
panic-halt = "0.2.0"
#panic-itm = "0.4.2"

[profile.release]
codegen-units = 1
debug = true
lto = true
