
# openocd -f interface/stlink.cfg -f target/stm32g0x.cfg

[target.thumbv6m-none-eabi]
runner = "arm-none-eabi-gdb -q -x ../openocd.gdb"


rustflags = [
	"-C", "link-arg=-Tlink.x"
]


[build]
target = "thumbv6m-none-eabi"